import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const outfit = Outfit({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark, // Set initial theme to dark as per ThemeProvider default
        variables: {
          // colorBackground: "oklch(var(--background))",
          // colorInputBackground: "oklch(var(--input))",
          // colorInputText: "oklch(var(--foreground))",
          // fontFamily: outfit.style.fontFamily,
        },
        elements: {
          // You can further customize individual elements here
          // For example:
          // formButtonPrimary: {
            // color: "oklch(var(--button-text))",
            // backgroundColor: "oklch(var(--destructive))",
          // },
        },
      }}
    >
      <html lang="en" className={outfit.variable} suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
